### PR TITLE
Three patches

### PR DESCRIPTION
**Pull request by LFriede**
Hi BuXXe,

i made some new patches.
First one adds support for multiple stream urls returned from the hoster resolution library.
Second one sets the "canonicalUrl" to the videos so Movian is able to continue them from the last timestamp and the "mark as seen" feature works correct.
Third patch adds the "searchbar" item to the plugin, the same what I did with your kinox plugin before.

### CODE REVIEW

**Comment by BuXXe** [comment]
Thx for the support. When i find some spare time i will merge and release the new plugin version for the movian plugin system.

**Comment by LFriede** [comment]
Nice =) Don't hurry with the release, bs.to has a new hoster, I'll add it to the hrl. I think I'll get it done this week.

**Comment by Invictaz** [comment]
Good news!  Don't forget to name it 0.7 as the version number now is 0.6

**Comment by BuXXe** [comment]
Its not my first release so i guess i will do it right ;)

**Comment by LFriede** [comment]
I pushed another commit fixing the hoster list. The plugin reads the `hoster-tabs` classed element from DOM. Previously the plugin uses only the first DOM element, now it iterates them to display all hosters.

**Comment by Invictaz** [comment]
Great news

**Comment by BuXXe** [comment]
yeah the site did not use multi line hosters. thx for the addition. anything more on the TODO before next version?

**Comment by LFriede** [comment]
Maybee that page.loading animation?

**Comment by BuXXe** [comment]
dont know if there still is this bug in which case the loading animation makes the system unresponsive to input
EDIT: forget about it, that was the overflow with the screensaver stuff

**Comment by LFriede** [comment]
I pushed another idea, the bs.to site has a random episode feature, I integrated it into the plugin. I'm using an icon from visualpharm.com, it is free as long as we link to their website. I've added the link to the description, if you don't like it we could make our own but I was to lazy :sunglasses:

**Comment by Invictaz** [comment]
Anyone did look at the new log I send in?

**Comment by LFriede** [comment]
I did but there is nothing new to see for me. Plz don't hijack my pull request ;)

**Comment by BuXXe** [comment]
sorry for the long wait, i still cannot figure out your problem Invictaz, sorry for that.
@LFriede  so are u finished with ur additions :D? Ready for release?

**Comment by LFriede** [comment]
I'd like to do that page.loading thing, hadn't much time the last days but i'll try to do it this weekend.

**Comment by LFriede** [comment]
Done, that's all I had on my list. I think we are ready for release if you accept the last fix for the hrl and update the submodule.

**Comment by BuXXe** [comment]
I manually merged the changes. I used a self made icon instead of the given Dice.svg and will close the pull request now. Added in 0.7 Release

**Comment by Invictaz** [comment]
@BuXXe That's too bad. I really was hoping that it was due to missing VPN or something. I don't have an additional one to test it out but since the new EU rules to partially remove geoblocking I may try again.

**Pull request closed without merging**
